name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use the Nodde.js version compatible with your Angular app

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install && npm i -save-dev @types/nodemailer

      # Step 4: Build the Angular app
      - name: Build Angular app
        run: npm run build --prod

      # Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}